version: "3"
services:
  backend:
    restart: always
    build:
      context: ./api
    env_file: .env
    ports:
      - ${API_MANAGEMENT_PORT}:${API_MANAGEMENT_PORT}
      - ${SOCKET_PORT}:${SOCKET_PORT}
    volumes:
      - ./api/configs:/go/src/gAPIManagement/api/configs/

  frontend: 
    build: 
      context: ./dashboard 
    restart: always
    ports:
      - ${FRONTEND_PORT}:80

  rabbitlistener:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile-rabbitlistener
    env_file: .env
    volumes:
      - ./api/configs:/go/src/gAPIManagement/api/configs/

  rabbit:
    restart: always
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    env_file: .env
    ports:
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
      - "${RABBITMQ_PORT}:5672"
    labels:
      NAME: "rabbitmq"
  
  elastic:
    restart: always
    image: elasticsearch:latest
    env_file: .env
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
      - "${ELASTICSEARCH_ALT_PORT}:9300"
    volumes:
      - ./elasticsearch/storage/data:/usr/share/elasticsearch/data

  mongodb:
    image: mongo
    restart: always
    env_file: .env
    volumes:
      - ./data:/data/db
    ports:
      - "${MONGO_PORT}:27017"