FROM golang:1.9

ENV RABBITMQ_HOST localhost
ENV RABBITMQ_PORT 5672
ENV RABBITMQ_USER guest
ENV RABBITMQ_PASSWORD guest
ENV RABBITMQ_QUEUE gAPI-logqueue


WORKDIR /go/src/
RUN mkdir -p /gAPIManagement/api
ADD . /go/src/gAPIManagement/api
WORKDIR /go/src/gAPIManagement/api

RUN echo $GO_HOME
RUN sh install.sh
RUN go build -o rabbit-listener ./rabbit-listener.go 

ARG db=mongo
ARG logs_type=Elastic
ARG queue_type=Internal

RUN sh generate_config.sh db=$db logs_type=$logs_type queue_type=$queue_type

CMD ["/go/src/gAPIManagement/api/rabbit-listener"]