#!/bin/sh
go get "github.com/patrickmn/go-cache"
go get "github.com/allegro/bigcache"
go get "github.com/valyala/fasthttp"
go get "github.com/qiangxue/fasthttp-routing"
go get "github.com/streadway/amqp"
go get "gopkg.in/mgo.v2"
go get "github.com/dgrijalva/jwt-go"
go get "github.com/googollee/go-socket.io"
go get "github.com/rs/cors"
go get "github.com/ulule/limiter"
go get "golang.org/x/crypto/bcrypt"
go get "github.com/go-ldap/ldap"
